[tool.poetry]
name = "advent-of-code-2024"
version = "0.1.0"
description = ""
authors = ["Grady Lynn <gradylynn314@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"

ipykernel = "^6.29.5"
torch = "^2.5.1"
numpy = "^2.1.3"
